### ISSUE TITLE
No system menu options for Debian ?

### ISSUE THREAD

**Issue by karuppiah7890** [alexanderepstein/Insomnia#29]
**Issue Label:** [Bug] 

**Description of bug or feature enhancement:** I don't see any system menu options on the top right for Insomnia like in the README gif in which I can choose preferences and stuff.

**OS and OS version:** Ubuntu 16.04

**Version of Insomnia Application:** Insomnia1.2.0 amd64

**Comment by alexanderepstein** [comment]
@karuppiah7890 

I use a distribution that uses Ubuntu as its basis and actually the version of Ubuntu you described is technically the one I'm on.

But that's weird, I noticed that if i try to run the application with sudo privileges this occurs but haven't seen it otherwise. Does this occur if you clone the repository and run the code in an uncompiled version? I want to know if what is broken here comes from the actual application, the packager that turns my application into a linux executable and an installer that turns the executable into a .deb .rpm etc.

**Comment by karuppiah7890** [comment]
No, I never get the Icon in my system menu. I run it with normal
privileges, and not even through CLI. But I just tried with CLI too, with
and without sudo, all lead to same result - no system menu icon. And yes, I
actually cloned once recently and tried the app like that too, and no, I
don't see the system menu icon. Only after learning from your README I
understood that I have to use system menu icon to reach settings, and all
this while I was searching for window based options on top left

**Comment by alexanderepstein** [comment]
try running 

   sudo apt-get install libappindicator1

I think I just found a dependency for this to work

**Comment by karuppiah7890** [comment]
Woah! Cool! Works now!! Thanks man :smile:

**Comment by karuppiah7890** [comment]
I guess I need to create an Electron App myself with all these features, to learn all the Ups and Downs.

**Comment by alexanderepstein** [comment]
@karuppiah7890 glad to hear it works :) I am going to add this code block to the readme so other people dont have the same problem in the future and yes it is definitely the best way to learn the framework. This is my first electron application with some tinkering and lots of google searches I haved seem to figure out the flow of electron

**Comment by karuppiah7890** [comment]
Cool. I once created a very simple electron app. But I didn't learn to bundle them properly, and for different OSs that too. And my executables were very big too. May be I will see your repo and other repos to see about bundling and how to make bundle size less. :smile:
